### ISSUE TITLE
Permission nodes?

### ISSUE THREAD

**Issue by Solidflip** [LatvianModder/FTBUtilities#30] opened 2016-01-24 23:00 UTC
I would like to allow a group of players to bypass claims. This seems to be a permission node as opped players can do it however those in Gamemode cant.. Is there somewhere i can see the permission nodes used? Or another way to affect this change?

**Comment by LatvianModder** [comment] 2016-01-25 12:53
I have planned to make permission nodes based system, but that will be in future, probably. It's not a problem for me to do it, the problem is how would I make this work with other mods

**Comment by LatvianModder** [comment] 2016-01-26 17:18
I actually came up with a good system, and I will maybe even make a PR in Forge repo, that would add a basic node system, if any mod wants to use it. But for now, here I made a list of how a basic player permissions list would look like:

"cmd.help": true,
"cmd.spawn": true,
"cmd.tell": true,
"cmd.home.*": true,
"ftbu.max_homes": 3,
"ftbu.crossdim_homes": true,
"ftbu.max_claims": 100,
"ftbu.max_loaded": 20,
etc.

**Closed** 2016-06-15 00:02 UTC
Labels: High Priority, Suggestion / ToDo

**Comment by H3roDude** [comment] 2018-10-21 10:50
And what are the permission nodes in 1.12.2 ?

**Comment by LatvianModder** [comment] 2018-10-21 10:54
https://github.com/LatvianModder/FTBUtilities/tree/master/guide/ranks/example_config
