### ISSUE TITLE
Server crash on onBlockBreak caused by fake players in claimed areas.

### ISSUE THREAD

**Issue by cri5ti** [LatvianModder/FTBUtilities#145] opened 2016-06-26 11:40 UTC
Server crash caused by Random Things block breaker in a claimed chunk, though I assume it will crash for other fake players.

```
java.lang.NullPointerException: Ticking block entity
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:51)
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9)
	at net.minecraft.server.management.UserList.func_152683_b(SourceFile:68)
	at net.minecraft.server.management.UserListOps.func_187452_a(SourceFile:30)
	at com.feed_the_beast.ftbl.util.FTBLib.isOP(FTBLib.java:318)
	at com.feed_the_beast.ftbl.api.permissions.rankconfig.RankConfig.getJson(RankConfig.java:50)
	at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.onBlockBreak(FTBUPlayerEventHandler.java:297)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_223_FTBUPlayerEventHandler_onBlockBreak_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:697)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:286)
	at lumien.randomthings.tileentity.TileEntityBlockBreaker.func_73660_a(TileEntityBlockBreaker.java:96)
	at net.minecraft.world.World.func_72939_s(World.java:1797)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Unknown Source)
```

The code in question is this: 

```
public static boolean isOP(GameProfile p)
{
    return !isDedicatedServer() || getServerWorld() != null && getServer().getPlayerList().getOppedPlayers().getPermissionLevel(p) > 0;
}
```

where I suspect `getPermissionLevel(p)` is causing the crash, so it might be a Forge bug.

For anyone else having the same issue, I've patched my server now by wrapping everything in a try catch and return false:

```
public static boolean isOP(GameProfile p)
{
    try {
        return !isDedicatedServer() || getServerWorld() != null && getServer().getPlayerList().getOppedPlayers().getPermissionLevel(p) > 0;
    } catch(Exception e) {
        return false;
    }
}
```

**Comment by LatvianModder** [comment] 2016-06-26 11:50
Actually I think it is caused by UUID being null (gonna go and yell at fake player mod's owner about that) so instead of try/catch I will check if(p != null && p.getId() != null)

**Comment by LatvianModder** [comment] 2016-06-26 12:18
15:13:16 <@lumien231> Will fix it in the next version
Getting fixed!

**Comment by LatvianModder** [comment] 2016-06-28 08:41
Fixed in pre2

**Closed by LatvianModder** 2016-06-28 08:41 UTC
Labels: Bug, High Priority
