### ISSUE TITLE
Chunkloader not working since latest update

### ISSUE THREAD

**Issue by ParAdoX83** [LatvianModder/FTBUtilities#373] opened 2017-03-05 17:15 UTC
Well title says it all. Whenever I leave the nether:

18:09:15 CONSOLE: thread/INFO] [journeymap]: ParAdoX83 joining dimension 0
18:09:41 CONSOLE: thread/INFO] [Actually Additions]: Unloading WorldData for world -1!
18:09:41 CONSOLE: thread/INFO] [FML]: Unloading dimension -1

So my cute netherpumps dont work for now :(

**Comment by LatvianModder** [comment] 2017-03-05 17:16
Which version specifically?

**Comment by ParAdoX83** [comment] 2017-03-05 17:17
FTBUtilities-1.10.2-3.4.2

**Comment by eobie** [comment] 2017-03-05 18:28
Yep... running Direwolf20 1.10.2. Doesnt work in latest release and not in the latest beta 1.7.0. Enderio pipes have to be broken and reattached for them to start working again. Railcraft locomotives stop dead on tracks with FTBU chunkloaders but work fine with the ExtraUtilities chunk loader.

**Comment by eobie** [comment] 2017-03-05 19:16
standby for enderio.. i logged out and it seems to still be working on 1.7.0 of Direwolf. Locomotives still do not work

**Comment by ParAdoX83** [comment] 2017-03-05 19:19
it makes extra utilties GP system going haywire though

![javaw 2017-03-05 20-18-49-796](https://cloud.githubusercontent.com/assets/26204374/23590476/153cc658-01e1-11e7-87c0-1f93bff7eeee.jpg)

![javaw 2017-03-05 20-19-27-077](https://cloud.githubusercontent.com/assets/26204374/23590478/19cc8578-01e1-11e7-93fc-f6e21c00bae7.jpg)

**Comment by LatvianModder** [comment] 2017-03-05 20:02
I think I found the problem: missing "!" before FTBUPermissions.canUpgradeChunk

https://github.com/LatvianModder/FTBUtilities/blob/1.9/src/main/java/com/feed_the_beast/ftbu/api_impl/ClaimedChunk.java#L48

**Comment by LatvianModder** [comment] 2017-03-05 20:05
Can someone check if this build works? http://mods.latmod.com/FTBUtilities/1.10.2-3.4.3/

**Comment by eobie** [comment] 2017-03-05 20:23
I wish I could... I would have to take down a running server and have all my users manually install this update which would be a total nightmare. I'll see what I can do. Why are there three files... I just need the plain jar, correct?

**Comment by LatvianModder** [comment] 2017-03-05 20:25
You only need to update it server side, clients dont need it

**Comment by LatvianModder** [comment] 2017-03-05 20:25
and yeah, the one without -tag

**Comment by eobie** [comment] 2017-03-05 20:26
Awesome.. standby!

**Comment by eobie** [comment] 2017-03-05 20:26
Will probably take a bit to get a report if it breaks, but I will install now.

**Comment by eobie** [comment] 2017-03-05 20:39
I removed the old JAR, replaced with new. Server did not start. Do I need to remove the local folder too?

**Comment by LatvianModder** [comment] 2017-03-05 20:47
if the server didnt start, maybe there's a crash report? Shouldnt delete the local folder

**Comment by eobie** [comment] 2017-03-05 20:48
[crash-2017-03-05_15.35.27-server.txt](https://github.com/LatvianModder/FTBUtilities/files/819733/crash-2017-03-05_15.35.27-server.txt)

**Comment by eobie** [comment] 2017-03-05 20:48
attached above..

**Comment by LatvianModder** [comment] 2017-03-05 20:52
Oh you gotta update.. FTBLib too http://mods.latmod.com/FTBLib/1.10.2-3.4.4/ eh.. I hope it doesnt break even more stuff...

**Comment by eobie** [comment] 2017-03-05 20:56
I'm stepping out of the house. Will test it as soon as I can. Will keep you updated. Thanks for all you do!

**Comment by eobie** [comment] 2017-03-05 20:58
Just to confirm, this is serverside only as well?

**Comment by LatvianModder** [comment] 2017-03-05 20:58
yes

**Comment by LatvianModder** [comment] 2017-03-05 20:59
I will upload the .jar on curse anyway, but I just need someone to test it, and thanks for doing that

**Comment by eobie** [comment] 2017-03-05 21:38
Ok... server started correctly. Will keep you updated..

**Comment by eobie** [comment] 2017-03-05 21:42
Server started but clients get a fatal error when joining. Reverted back to old files.

**Comment by eobie** [comment] 2017-03-05 21:44
[2017-03-05-7.log.gz](https://github.com/LatvianModder/FTBUtilities/files/819777/2017-03-05-7.log.gz)

Will this help..

**Comment by LatvianModder** [comment] 2017-03-05 21:48
Oh, so this one does need client update. Well, darn. Do you have a custom pack, or a public pack?

**Comment by eobie** [comment] 2017-03-05 22:02
Public. Direwolf20 1.10.2 version 1.7.

**Comment by ParAdoX83** [comment] 2017-03-07 13:18
Appears to be working now 👍

**Comment by eobie** [comment] 2017-03-07 13:32
has the fix been included in FTB Beyond?

**Comment by LatvianModder** [comment] 2017-03-08 13:35
Yeah

**Comment by efflicto** [comment] 2017-03-28 18:44
Hey,

still having this issue. Updated to FTBLib-1.10.2-3.4.5 and FTBUtilities-1.10.2-3.4.4 but the chunks getting not loaded. 
I placed a Woot Mobfarm, a Rftools Builder and a Environmental Tech Ore Miner in the Mining Dimension of aroma1997 but soon as I leave the dimension the chunks getting unloaded I think. All machines stopped working. 
I'm playing the FTB Beyond modpack in version 1.2.1.

**Comment by crysyn** [comment] 2017-04-05 06:09
Ok I know this is supposed to be closed but this still happens on Skyfactory 3's current version (3.0.8)

Steps to Reproduce:
- Setup a system across chunk boundaries (I use EnderIO)
- Claim one of the chunks (left click) and then chunk load it (shift left click)
- Leave the area and return it should work ok.
- Unclaim the chunks by using the Unclaim All button in the top right
- Leave and come back.
Should see a general state of disarray. If not just leave and come back again.

What appears to have happened (and maybe this was what was resolved, I dunno) is that this did not really unload the chunks when I unclaimed them all. (Maybe the UI assumes if its not claimed it cant be loaded). What led me to this was my power system was completely drained and it shouldnt be.. a full recharge (25M RF) of my system only takes around 50-60 buckets of oil.. all 1000 buckets were gone in 24 hours with only me around for 1-2 hours.

Anywho, in-game solution: Claim the chunks again, load the chunks again and then unload them by shift-right-click.. This puts them into the proper state.. Should be able to jump in and out of the chunks and the systems should load and reconnect properly.

Hope this helps whoever comes by next to see what is going on.

**Comment by LatvianModder** [comment] 2017-04-05 10:35
Try this with 3.5.0 versions, I changed some stuff there

**Comment by crysyn** [comment] 2017-04-05 17:51
Will do if I have some time, right now I dont have enough time to play SF3 as much as I want :D

**Comment by ktole1999** [comment] 2017-04-05 17:55
from what i have read in eio tracker is that if conduits cross boundary to an unloaded chunk the conduit will load it to finish the transaction to keep item/fluid/power from being voided. not sure if this is what you are referring to.

**Comment by crysyn** [comment] 2017-04-05 18:35
This is a combination of issues (which may be fixed) between the mods. First bug is that removing a claim on a chunk via the remove all did not apparently release it from being chunk loaded (implies you could load over the limit of chunks if you claim an area, load it, release all, claim a new area, load it, release all, etc... ). This is speculation but it would coincide with the confusion that end ensued.. This may all be fixed though I have not had an opportunity to test it on the newer versions.

Now in regards to the other mods what you say just reinforces this being the issue but its happening in the opposite way you are thinking. When part of the system is loaded and then a section of it is removed I believe that it can not tell if this was because the chunk was unloaded or because an action removed it. The block gone notification is likely the same and so it would be removed. Then when the person comes back the chunk with the active system in it is -already- loaded... Its not going to look for the parts it thinks are removed and so you get into the state where a visually connected system is acting as two separate systems broken down the chunk boarders. This is also why just removing a part and putting it back in so the system rescans all connected parts will restore it to a working state.

Again.. All speculation I have not looked at the code for this mod or any of the others I am just taking what I am seeing and what I have been told and seeing if the pieces all fit together... Also, as noted by the owner above, this could likely be resolved.. I just have not tested it and the mod pack I am using is using the 3.4.3 version, not the 3.5.0 mentioned to resolve the issue.

**Comment by HenryLoenwind** [comment] 2017-04-05 20:32
@crysyn That analysis sounds plausible---however, it doesn't fit all observed error cases. In one instance we had a straight line of 6 circuits, the first 3 on extract, the next 3 on insert. The error showed as the middle 4 conduits doing nothing.

**Comment by LatvianModder** [comment] 2017-04-06 07:46
Im gonna close this one and move to #360 because that one is older

**Closed by LatvianModder** 2017-04-06 07:46 UTC
Labels: Bug

**Comment by mikeschuld** [comment] 2017-10-25 01:25
Is it possible to get a build of this for 1.7.10 with the missing "!" line fixed? The latest FTB Infinity Evolved pack is using a broken version.

**Comment by LatvianModder** [comment] 2017-10-25 19:01
No, old packs won't get updated anyway, and I ain't backporting the whole mod to an ancient version like 1.7, which is currently 5 major versions behind current most popular one

**Comment by mikeschuld** [comment] 2017-10-28 02:06
I wasn't worried about the pack being updated, I'd just drop the new jar in myself. A whole backport shouldn't be necessary for a single character addition and a recompile. I guess I'll just find a tutorial and compile it myself.
