### ISSUE TITLE
Starting Items only provide 1 item 

### ISSUE THREAD

**Issue by Alaberti** [LatvianModder/FTBUtilities#72] opened 2016-03-04 17:04 UTC
Using version 1.7.10-1.0.17.6 - the starter apples that are set to 16 only give 1, and additional entries also only provide 1 regardless of how many you declare. Deleting and reloading default configs do not work either.

**Comment by smbarbour** [comment] 2016-03-15 05:43
This is caused by GameRegistry.makeItemStack ignoring the stack size parameter:  https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/fml/src/main/java/cpw/mods/fml/common/registry/GameRegistry.java#L530

Additionally, the parameter order is makeItemStack(String itemName, int meta, int stackSize, String nbtString) while the FTBLib code calls GameRegistry.makeItemStack(itemID, size, dmg, nbt)

i.e. size and dmg are reversed

**Comment by smbarbour** [comment] 2016-03-15 05:52
https://github.com/LatvianModder/FTBLib/pull/18 contains a fix for this issue.

**Comment by LatvianModder** [comment] 2016-03-15 18:14
Fixed in that ^

**Closed by LatvianModder** 2016-03-15 18:14 UTC
Labels: Bug
