### ISSUE TITLE
Major Syncing Issues with FTBU.

### ISSUE THREAD

**Issue by KaneHart** [LatvianModder/FTBUtilities#84] opened 2016-03-21 19:59 UTC
So we have had since the Start of Infinity Expert with FTBU Being added a lot of syncing issues mainly using a none default gamemode like Expert mode. (Mainly if not only a MP Bug Issue)

This issue is also outside the pack but since Infinity Expert mode is one the most played packs / features of this I thought I use it as an example.

A lot of times in Multiplayer you might end up with the wrong recipes. If it's a custom recipe the Admin of the server added or even if their using expert mode but some reason it's syncing Normal Mode recipes.

It has become such an issue in MP Games for us that we just ended up writing top common recipe changes on our forums for people to check.

The client Reload seems to have 0 effect as well for us. 

Last tested with version 
FTBUtilities-1.7.10-1.0.17.6.jar
FTBLib-1.7.10-1.0.17.6.jar

**Comment by LatvianModder** [comment] 2016-03-21 21:19
I had already created an issue at the same time, but eh, yours is better :P
https://github.com/LatvianModder/FTBUtilities/issues/83

**Comment by LatvianModder** [comment] 2016-03-21 21:21
And the problem is super simple - it doesn't reload your client when you join the server. A simple fix, but next time this happens, you don't have to /reload, you can also /reload_client. I think :v

**Comment by KaneHart** [comment] 2016-03-22 00:43
Issue is most people are not finding /reload_client working in fact idk if it has ever worked for them I have to ask again.

**Comment by LatvianModder** [comment] 2016-03-23 14:12
Seems to be a sync problem here too: https://github.com/LatvianModder/FTBUtilities/issues/86

**Comment by cblair91** [comment] 2016-03-23 14:29
Just a heads up on this, some of the issue might be down to two loading calls.

http://pastebin.com/WhjTBbkL
It loads server-side scripts on preJoin (line 14), and then RE-initializes on join (line 68). It's on the join event that it fails to get server-side scripts and removes them.

**Comment by LatvianModder** [comment] 2016-03-24 13:07
From what I tested, it seems like it is a server-side issue. It syncs ok, but it doesnt reload things properly, as cblair91 said. Its weird, because /reload calls exaclty the same function

**Comment by LatvianModder** [comment] 2016-03-24 20:41
Should be fixed in 1.0.18, or at least, a workaround is there

**Closed by LatvianModder** 2016-03-24 20:41 UTC
Labels: Bug
