### ISSUE TITLE
[1.10.2] Server Crashes after Player Logs In.

### ISSUE THREAD

**Issue by ADeathyTouch** [LatvianModder/FTBUtilities#390] opened 2017-03-20 22:42 UTC
So this is by far the strangest thing I have seen. At random points in time any given player can be disconnected and then when they log back in it crashes the server with this as a crash log. http://pastebin.com/fNgaFQBc  So far to fix this all I have been able to do is TP them away from where they were when they log in via console or in-game commands.  On one rare instance when the player logged back in it did not crash the server but instead it disconnected all players and no players could reconnect without a manual restart of the server. I didn't get a crash report for that seeing as it didn't technically crash but I did get the last two logins from the log which is here. http://pastebin.com/K7YMRfXu  If you need any further information I would be more than happy to attempt to get it.  The server is running FTB Beyond V1.0.1.

**Comment by eobie** [comment] 2017-03-22 22:24
This most likely isn't a problem with ftbu. I had something similar happen on my server. A player had bugged a woot item. When he would log on it would chunkloading that chunk, send power to broken structure and the server would crash. We had to go over to his base and break the block and then all was good.

**Comment by ADeathyTouch** [comment] 2017-03-23 19:57
Several of the players that have had this happen when they logged had never touched Woot.

**Comment by ktole1999** [comment] 2017-03-23 20:18
are they logging in to a common area?

**Comment by eobie** [comment] 2017-03-23 20:28
You're focusing on woot, don't. Focus on the problem. Something is causing the server to crash when that chunk is loaded. Go investigate the chunk.

**Comment by ADeathyTouch** [comment] 2017-03-23 22:04
I have scanned each and every chunk extensively if I thought it were anything other than FTBU then I would have gone elsewhere to report it.

**Comment by eobie** [comment] 2017-03-23 22:07
I'm only trying help because I had the same issue. What exactly is the cause for thinking it was ftbu?

**Comment by LatvianModder** [comment] 2017-04-05 14:37
Should be fixed in 3.5.0

**Closed by LatvianModder** 2017-04-05 14:37 UTC
