### ISSUE TITLE
Claim Command

### ISSUE THREAD

**Issue by anar4732** [LatvianModder/FTBUtilities#130] opened 2016-06-03 23:41 UTC
Add a command to:
claim chanks protection enable and diasble.

sometimes all claimed chanks
you have to disable and re-enable it after a while

================================
=== translated by Google translation ====
================================

**Comment by AKTheKnight** [comment] 2016-06-04 09:53
This is a duplicate of #111

**Closed** 2016-06-04 17:29 UTC
Labels: Duplicate
