### ISSUE TITLE
Chunk loaded chunks randomly unload

### ISSUE THREAD

**Issue by ghost** [LatvianModder/FTBUtilities#565] opened 2017-11-02 00:35 UTC
I constantly have to chunk load claimed chunks again and again; they seem to randomly become unloaded.

I am running a LAN server.

FTBLib version: 4.2.3
FTBU version: 4.2.2
MC version: 1.12.2
Modpack: ATM 3, v4.4

**Comment by Horras64** [comment] 2017-11-03 08:20
I don't have run a LAN server however on my singleplayer world I run into this exact same issue with my chunks becoming unloaded when I log in. Same Modpack and versions.

**Comment by PapiDimmi** [comment] 2017-11-06 23:52
This happens almost every single time I enter the world. It’s really annoying.

**Comment by LatvianModder** [comment] 2017-11-08 23:01
Unload as in, dont stay force loaded or unload like, you have to mark them as loaded in GUI? Doesn't happen to mine, maybe I'm just not doing something you are

**Comment by PapiDimmi** [comment] 2017-11-09 04:33
Claimed chunks that I have chunk loaded often revert back to non-chunk loaded chunks (albeit they are still claimed) after leaving the world and re-entering it.

**Comment by PapiDimmi** [comment] 2017-11-12 04:31
It happens basically every time I enter the world.

**Comment by PapiDimmi** [comment] 2017-11-12 04:46
It happens basically every time I enter the world.

That’s not all, though. Upon losing my chunk loaded chunks, when I try to load them again, the red squares don’t appear. I have to restart the game in order for them to appear.

**Comment by LatvianModder** [comment] 2017-11-12 11:39
Maybe enable chunkloading logging in FTBUtilities config, and see what it prints in log

**Comment by PapiDimmi** [comment] 2017-11-13 02:45
I’m not sure what, exactly, to look for in the log; however, I think I know what causes this.

These bugs (chunk loaded chunks being unloaded and the red squares not appearing) seem to always happen when I restored to a backed up save folder (i.e., replacing the world save folder with an older backup).

**Comment by LatvianModder** [comment] 2017-11-13 10:53
..and you do that very often why? This bug shouldnt happen in that case anyway, but if you have to restore backups a lot, something else is wrong with your world too :P

**Comment by PapiDimmi** [comment] 2017-11-13 13:22
Sometimes I’ll do it if I feel that my death was unjustified—i.e., lag or a glitch.
I might also restore to a backup if my world becomes corrupt (which has happened), or if a glitch causes me to lose items, experience, etc.

I know most people don’t do that, but still, it’d be great if I didn’t have to re-chunk load chunks every time I do it.

**Comment by PapiDimmi** [comment] 2017-11-14 06:06
Actually, I’m pretty sure it doesn’t just happen when I restore to a backup.
I think it happens every time I leave and re-enter the world or just whenever I die, since it just happened to me in-game when I didn’t even restore to a backup.

**Comment by LatvianModder** [comment] 2017-11-14 17:20
I will fix it, but I have to figure out where it comes from :P

**Comment by PapiDimmi** [comment] 2017-11-15 01:51
I _just_ restarted my game and restored to a backup, and my chunk loaded chunks remained.

Honestly, I have no clue what’s causing this.

@Horras64 Since you’re having the same problem as I’m having, do you know what possibly causes this? Is there any consistency for you?

**Comment by Horras64** [comment] 2017-11-15 07:53
I obviously don’t know what causes the issue. However it occurs whenever I enter a world, reload all the chunks, exit the world, and re-enter.

**Comment by PapiDimmi** [comment] 2017-11-19 06:23
This hasn’t happened in a while. It seems to be fixed, even though I’m still using the same version of FTBU. That’s odd.

**Comment by PapiDimmi** [comment] 2017-11-19 06:24
This hasn’t happened to me in a while. It seems to be fixed, even though I’m still using the same version of FTBU. That’s odd.

**Comment by LatvianModder** [comment] 2017-11-19 13:00
Well, as the title says, `randomly`

**Comment by PapiDimmi** [comment] 2017-11-19 15:33
Yeah, but it used to happen all the time. Now it never happens.

**Comment by PapiDimmi** [comment] 2017-11-20 15:12
Never mind. It happened again.

**Comment by PapiDimmi** [comment] 2017-11-24 18:07
It basically happens every time I load my world now, and I have to restart the game to chunk load chunks again.

It’d be great if you could try to figure out what’s causing this and maybe fix it.

**Comment by LatvianModder** [comment] 2017-11-24 19:25
oh singleplayer? I didnt really test for singleplayer, only dedicated server... it never unloads in my SP tho

**Comment by PapiDimmi** [comment] 2017-11-24 19:28
I am hosting a LAN server.

**Comment by AnkaraSoulreaver** [comment] 2017-11-25 15:01
My issue is related to a solo play server as well.  Nothing really new to add but I also experience the situation where every time I log out of the solo server and log back in, chunk load is lost and squares will not re-highlight to red.  Claimed chunks works fine at all times.

**Comment by uecasm** [comment] 2017-11-26 03:38
When I first started using the DW20 1.12 modpack (single player) I could exit and reload several times without any issues -- chunks would stay marked as loaded.  Then the modpack updated (including an update to FTBUtils) and now the chunks remain claimed but not loaded every single time I load the world.  However the squares to re-highlight to red when I re-chunk-load them -- except once, where the colour didn't change but the count at the bottom still did.

**Comment by PapiDimmi** [comment] 2017-11-26 14:50
It seems like we’re all having the same issue.

One of three things happens when I enter my world:
1. My chunks stay chunk loaded.
2. My loaded chunks have been reset, but I can re-chunk load them just fine.
3. My loaded chunks have been reset, and I can re-chunk load them (the count at the bottom changes when I shift + right-click a claimed chunk); however, when I re-chunk load my claimed chunks, the squares do not turn red, and I have to restart my game for them to turn red again.

It seems to be completely random. I have no clue what causes this, and I haven’t noticed any pattern.

**Comment by fguillod** [comment] 2017-11-30 15:15
Hi, I'm running into the same issue with the Direwolf20 1.12 pack (either with the 1.1.0 or the 1.2.0 version of the pack). I'm playing in singleplayer.

Each time I relog into the game, all chunk-loaded chunks are no more loaded (0/50). The red border also almost never appears on the map, and even if it appears, the chunks won't be chunk-loaded anymore the next time I load the game.

This issue happens everytime I load a game, not just randomly.

**Comment by PapiDimmi** [comment] 2017-11-30 16:13
Just a note: this happens in 1.12.2 but _not_ 1.10.2.

**Comment by LatvianModder** [comment] 2017-11-30 20:41
Ok, happened for me too - first time joining world after start is ok, I close the world, re-open it, and the gui is broken. It must be some cache error/desync which causes to actually unload chunks

**Comment by AtirixGaming** [comment] 2017-12-04 16:36
This Bug is happening to me to.
Can we do something about it. For example downgrade or doing something on the configs?

**Comment by AnkaraSoulreaver** [comment] 2017-12-04 16:39
I’ve just been fully shutting my game down after each session and that
works. But if rather not have to do all the pre-initialization steps every
time.

**Comment by jinks** [comment] 2017-12-09 01:24
Just to add to the list, it's still happening in DW20 1.3.0. Claimed chunks stay claimed, loaded chunks get unloaded (info in bottom right is 0/MAX).

FTBLib version: 4.2.5
FTBU version: 4.2.4

Some observations:
- It happens every time I close and re-open a world (singleplayer)
- It doesn't happen when I completely restart MC
- It happens when MC crashes for some reason (in my case the crash was OptiFine's fault, NPE rendering tile entity...)

It *looks* like FTBU is at some point wiping its chunk list and re-creating it and things go wrong when it gets interrupted right between those 2 actions. The usual remedy in the general case for cached date is to make sure to always use some form of atomic replace for the on-disk data, which is harder than it sounds.

**Comment by number65259** [comment] 2017-12-10 22:37
Same problem with the most recent Direwolf pack on 1.12. Log in, chunks are unloaded. They can occasionally be reloaded. Once, the chunkloaded counts in the bottom right would iterate but there would be no visual indicator on the map.

**Comment by Lordeath19** [comment] 2017-12-13 15:03
I snooped around the code and the saves folder and it appears that inside: saves/world/data/ftb_lib/teams/insert_team.dat
you only store the claimed chunks but not the loaded chunks. 

might be talking none-sense tho...

**Comment by LatvianModder** [comment] 2017-12-13 15:13
It's stored as "chunk upgrade". Some entries are saved as `{x:123,z:123}` and some as `{x:123,z:123,loaded:true}`. I dont list properties that are false to save space

**Comment by GreatSpoon** [comment] 2017-12-13 15:43
Any news on a possible fix? I have to go to 4-5 RF tools dimensions to re load all the chunks I want every time i start up a SP world.

Thanks for all the work you do.

**Comment by ZeroXx147** [comment] 2017-12-13 16:03
So i'm having the same problem since the last update, on Dec 4th. Just as everyone, everytime i relog the loaded chunks are gone, but not the claimed ones. @LatvianModder what does the entries have to do with all this? it's something that can be changed to fix th problem?

**Comment by cpw** [comment] 2017-12-24 03:09
I just reviewed your chunkloading code and it's not surprising this is happening. When forge tells you it's got chunks loaded for you, the first thing you do is remove the chunks from forge's chunkloading???!

You don't seem to be buffering them for reloading elsewhere either (and frankly that's bad, if the chunk is in an alternate dim, by telling forge to remove them, the world will unload and then you won't ever be able to get the chunks back).

Quite frankly, this is all round bizarro.

**Comment by LatvianModder** [comment] 2017-12-25 08:55
I know it is, but you know there isn't exactly a tutorial on how to make block-less chunkloaders that depend on permissions <.<

**Comment by LatvianModder** [comment] 2017-12-25 08:59
It should load them later btw, then `DimensionManager.getWorld(dimension)` forces dimension to be loaded, doesn't it?

**Comment by bs2609** [comment] 2017-12-25 14:13
Nope

**Comment by LatvianModder** [comment] 2017-12-25 19:31
Sorry, I meant `MinecraftServer.getWorld(dimension)`, that's what I'm using. That loads dimension when called, if it isn't loaded already

**Comment by uehlbran** [comment] 2017-12-26 21:57
Whatever you're doing isn't working. As soon as you re-log it resets all loaded chunks but keeps claimed chunks.

**Comment by UncleCrustyMC** [comment] 2017-12-29 16:04
From reading the comments above- this issue is only presenting in a single player world, OR when you restart a server world, yes? 
Thank you for all your hard work Lat :)
 Happy Holidays!

**Comment by LatvianModder** [comment] 2017-12-29 18:46
Thank you! It's unclear *when* exactly it occurs, but sometimes when world is unloaded

**Comment by cryzed** [comment] 2017-12-31 21:18
Any ideas when this issue will be fixed? I'm playing "FTB Presents Direwolf20 1.12" singleplayer, and each time I leave the world and re-enter it, all my chunks are claimed (as already reported), but chunks that had been marked as chunk-loaded are not anymore -- me having to visit each spot in person and chunk-loaded it again is quite bothersome. The issue is not random at all, it's clear when it happens.

**Comment by Nulreference** [comment] 2018-01-01 09:02
so i have something to add to this.

playing dirwolf20 1.12.2 v 1.4 pack i found the following weirdness
i broke my chunkloader to move it and forgot to put it back in a base rebuild
everything seemed to be working fine until i went fortress hunting in the nether
whenever i got a stutter from loading or generating a lot of chunks by sprint flying with my angel ring i would suddenly fall further testing in the nether showed even moving slow it would happen but far less commonly even more rarely just floating in the sky i would fall.
replaced block form chunk loader and the problem is totaly gone

so somehow the chunk rendering code is unloading chunks somehow(i think)
if needed im sure i can reproduce it on video im not sure if i can pull logs to go with it but im willing to try

**Comment by cryzed** [comment] 2018-01-01 14:04
@Nulreference what physical chunkloader are you talking about? FTBUtils loads chunks based on marked tiles on a special minimap, accessible through the inventory overlay -- I think you might be talking about another mod.

**Comment by Nulreference** [comment] 2018-01-01 20:33
no i used the minimap chunk loader and it intermittently fails but when i add the chicken chunks loader everything is stable the ftbutils minimap chunk system has some issue with keeping chunks loaded if you are in another dim. as i said i can provide video of whats happeneing.

using ONLY ftb utils to chunk load my water mills i get results as described in the nether further testing show this also happens in the end and the deep dark. the overworld is solid so far 
when i put the chicken chunks loader down next to my water mills i can fly anywhere/everywhere with no drop outs or weirdness

**Comment by Stray216** [comment] 2018-01-29 07:28
This is happening to me too. Just like described above.

**Comment by Protoskull** [comment] 2018-02-01 19:25
yn3n kos o5t rbk fuck the god that created everything you hold dear you waste of fucking space, air, blood, tears and cum 

go fucking die i na fucking shithole while sucking my huge thick ass dildo you fucking negroid

fuck all of you you stupid sons of cocksucking dickriding shitstains on this niggerfucking earth
(★ ͡° ͜ʖ ͡° 💧 )(★ ͡° ͜ʖ ͡° 💧 )(★ ͡° ͜ʖ ͡° 💧 )(★ ͡° ͜ʖ ͡° 💧 )(★ ͡° ͜ʖ ͡° 💧 )I'd rather masturbate with a jar full of scorpions to down-syndrome necrophilia midget porn than tolerate my luck, the entirety of fucking life, and this fucking pansy-ass shit-bucket of existence. Fuck EVERYONE AND EVERYTHING. Fuck this dick-riding, pussy-licking, half-legged, dickless sack of rotten cock-nobbing, shit-eating world. Humanity can drink acid from a hornet's fucking nest and go fuck itself raw. All those absolutely fucking retarded, mentally-deficient, god-damn mutated, AIDS-infested, cum-dripping, sour-note, flatter than their girlfriend's flexible tempo fuck-holes can eat a 5-ton barrel of pickled fucking dicks. Those utter bunch of kentucky-motherfucking-fried dry pieces of kung-pao fucking clits. Everyone that has ever existed and will exist can go butt-fuck their ebola-drinking ass-stapled mothers in hell's fuck-fest. They can suck on my 10-meter, thick juicy fucking dick while being raped by 69 billion cum-guzzling monkey-shaped black rusty fucking dildos and deep-throating a thick-skinned fuck-lizard's huge fucking prick. This total dog-shit bouquet of gang-banged, 0-iq, cataclysmic sacks of teddy-bear-hugging, flesh-light-using, 5-year-old orgy of ugly-ass motherfuckers can put their fucking dicks and gaping tight assholes in a blender, and this fucking universe, from the Big fucking Bang, till God's death, can get fucked back to the fucking stone age. 
![download](https://user-images.githubusercontent.com/20542262/35698655-6400dd90-0796-11e8-93e5-93e55301f92f.jpg)

**Comment by LatvianModder** [comment] 2018-02-04 00:56
@cpw Well, is this the correct way? Seems to be working now https://github.com/LatvianModder/FTBUtilities/blob/master/src/main/java/com/feed_the_beast/ftbutilities/data/FTBULoadedChunkManager.java#L69-L83

**Comment by scotty9090** [comment] 2018-02-22 04:05
I'm having further problems in that not only do the chunks unload themselves, but I cannot re-load them in the mini-map - i.e. they show up as claimed but not loaded and I cannot and no amount of shift-clicking will mark them as chunkloaded again.  Sometimes, a full restart will fix this - simply re-logging does not.

**Comment by uecasm** [comment] 2018-02-22 07:49
@scotty9090 Keep an eye on the loaded chunks count at the bottom.  The most common way this manifests is that the chunks in the map will not change colour when you shift-click them to re-load but the loaded chunk count *does* go up.  You can also verify this by explicitly un-loading and re-loading them and watch the count go down and up.

**Comment by ElvenChaos** [comment] 2018-02-22 20:14
@LatvianModder Should the changes be pushed so players have a chance to test?

**Closed** 2018-03-05 00:47 UTC
Labels: Bug, Important
